import type { TMenuApiItem } from '~/types/menu'

const mockMenuItems: TMenuApiItem[] = [
  {
    id: 'home',
    type: 'system',
    code: 'home',
    title: '首頁',
    enabled: true,
    order: 1,
  },
  {
    id: 'sample',
    type: 'system',
    code: 'sample',
    title: '範例頁',
    slug: 'sample',
    enabled: true,
    order: 2,
  },
  {
    id: 'examples',
    type: 'system',
    code: 'examples',
    title: '多層選單',
    slug: 'examples',
    enabled: true,
    order: 3,
    children: [
      {
        id: 'examples-basic',
        type: 'system',
        code: 'examples',
        title: '基礎元件',
        slug: 'basic',
        enabled: true,
        order: 1,
        children: [
          {
            id: 'examples-button',
            type: 'system',
            code: 'sample',
            slug: '',
            title: '按鈕元件',
            enabled: true,
            order: 1,
          },
          {
            id: 'examples-card',
            type: 'system',
            code: 'sample',
            slug: 'card',
            title: '卡片元件',
            enabled: true,
            order: 2,
          },
        ],
      },
      {
        id: 'examples-interactive',
        type: 'system',
        code: 'examples',
        title: '互動元件',
        slug: 'interactive',
        enabled: true,
        order: 2,
        children: [
          {
            id: 'examples-accordion',
            type: 'system',
            code: 'sample',
            slug: 'accordion',
            title: 'Accordion',
            enabled: true,
            order: 1,
          },
          {
            id: 'examples-navigation',
            type: 'system',
            code: 'examples',
            title: '分頁與導覽',
            slug: 'navigation',
            enabled: true,
            order: 2,
            children: [
              {
                id: 'examples-pagination',
                type: 'system',
                code: 'sample',
                slug: 'pagination',
                title: 'Pagination',
                enabled: true,
                order: 1,
              },
              {
                id: 'examples-breadcrumb',
                type: 'system',
                code: 'sample',
                slug: 'breadcrumb',
                title: 'Breadcrumb',
                enabled: true,
                order: 2,
              },
            ],
          },
        ],
      },
      {
        id: 'examples-layout',
        type: 'system',
        code: 'examples',
        title: '版型元件',
        slug: 'layout',
        enabled: true,
        order: 3,
        children: [
          {
            id: 'examples-header',
            type: 'system',
            code: 'sample',
            slug: 'header',
            title: 'Page Header',
            enabled: true,
            order: 1,
          },
        ],
      },
    ],
  },
]

export default defineEventHandler((): TMenuApiItem[] => mockMenuItems)
